services:
  squid-tp:
    image: alexlanu/squid-tp:latest
    container_name: squid-tp
    network_mode: host
    restart: unless-stopped
    volumes:
        - ./config/:/etc/squid:ro
        - ./logs:/var/log/squid/:rw
