http_port 3129 intercept
https_port 3130 intercept ssl-bump dynamic_cert_mem_cache_size=4MB tls-cert=/etc/squid/ssl/squid.pem
ssl_bump peek all
ssl_bump splice all
sslcrtd_program /usr/local/squid/libexec/security_file_certgen -s /var/lib/squid/ssl_db -M 4MB
